version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pki-2fa-app

    ports:
      - "8080:8080"

    environment:
      TZ: "UTC"

    volumes:
      # persistent seed storage
      - seed-data:/data

      # cron job output
      - cron-output:/cron_output

      # mount key files as read-only
      - ./keys/student_private.pem:/app/keys/student_private.pem:ro
      - ./keys/student_public.pem:/app/keys/student_public.pem:ro
      - ./keys/instructor_public.pem:/app/keys/instructor_public.pem:ro

      # mount cron job
      - ./cron/2fa-cron:/cron/2fa-cron:ro

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
